# -*- coding: utf-8 -*-
"""
Example script to generate analysis reports from simulation results.

This script demonstrates how to load simulation data (e.g., from CSV files
generated by run_simulation_batch.py), perform analysis, generate plots,
and save a summary report (e.g., Markdown or PDF).
"""

import argparse
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import glob
from typing import List

# Adjust import paths if needed
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from src.slot_game_theory.utils import helpers

# --- Data Loading ---

def load_simulation_data(file_paths: List[str]) -> pd.DataFrame:
    """Loads and concatenates simulation results from multiple CSV files."""
    all_data = []
    for path in file_paths:
        try:
            df = pd.read_csv(path)
            print(f"Loaded data from: {path} ({len(df)} rows)")
            all_data.append(df)
        except FileNotFoundError:
            print(f"Warning: File not found at {path}. Skipping.")
        except Exception as e:
            print(f"Warning: Could not load or parse {path}. Error: {e}. Skipping.")

    if not all_data:
        print("Error: No valid simulation data loaded.")
        exit(1)

    combined_df = pd.concat(all_data, ignore_index=True)
    print(f"Combined data shape: {combined_df.shape}")
    return combined_df

# --- Analysis and Plotting ---

def generate_summary_statistics(df: pd.DataFrame) -> pd.DataFrame:
    """Calculates summary statistics for key metrics across batches."""
    # Metrics to summarize
    metrics = ['rtp', 'variance', 'hit_frequency', 'bonus_frequency', 'expected_payout_per_spin']
    # Filter out potential non-numeric or problematic columns before describing
    numeric_df = df[metrics].apply(pd.to_numeric, errors='coerce')
    summary = numeric_df.describe()
    print("\n--- Summary Statistics ---")
    print(summary)
    print("------------------------")
    return summary

def plot_metric_distribution(df: pd.DataFrame, metric: str, output_dir: str):
    """Generates and saves a histogram/KDE plot for a given metric."""
    if metric not in df.columns or df[metric].isnull().all():
        print(f"Warning: Metric '{metric}' not found or contains only NaNs. Skipping plot.")
        return

    plt.figure(figsize=(10, 6))
    sns.histplot(df[metric].dropna(), kde=True, bins=20)
    mean_val = df[metric].mean()
    median_val = df[metric].median()
    plt.axvline(mean_val, color='r', linestyle='--', label=f'Mean: {mean_val:.4f}')
    plt.axvline(median_val, color='g', linestyle='-', label=f'Median: {median_val:.4f}')
    plt.title(f'Distribution of {metric.replace("_", " ").title()} Across Batches')
    plt.xlabel(metric.replace("_", " ").title())
    plt.ylabel('Frequency')
    plt.legend()
    plt.grid(axis='y', alpha=0.5)

    plot_filename = f"{metric}_distribution.png"
    plot_path = os.path.join(output_dir, plot_filename)
    try:
        plt.savefig(plot_path)
        print(f"Saved plot: {plot_path}")
        plt.close() # Close the plot to free memory
    except Exception as e:
        print(f"Error saving plot {plot_path}: {e}")


# --- Report Generation ---

def generate_markdown_report(summary_stats: pd.DataFrame, output_dir: str, input_files: List[str]):
    """Generates a simple Markdown report summarizing the results."""
    report_path = os.path.join(output_dir, "simulation_report.md")
    plots_available = [f for f in os.listdir(output_dir) if f.endswith('.png')]

    print(f"\nGenerating Markdown report: {report_path}")

    with open(report_path, 'w') as f:
        f.write("# Simulation Analysis Report\n\n")
        f.write(f"Generated on: {helpers.time.strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write("## Input Files\n\n")
        for file in input_files:
            f.write(f"- `{os.path.basename(file)}`\n")
        f.write("\n")

        f.write("## Summary Statistics\n\n")
        f.write(summary_stats.to_markdown())
        f.write("\n\n")

        f.write("## Metric Distributions\n\n")
        if plots_available:
            for plot_file in sorted(plots_available):
                metric_name = plot_file.replace('_distribution.png', '').replace('_', ' ').title()
                f.write(f"### {metric_name}\n\n")
                f.write(f"![{metric_name} Distribution]({plot_file})\n\n")
        else:
            f.write("No distribution plots were generated.\n")

    print("Markdown report generation complete.")


# --- Function to be called from main.py ---

def generate_report(data_path: str, output_dir: str, template: str = "standard"):
    """
    Wrapper function called from main.py to generate reports.
    
    Args:
        data_path: Path to simulation or optimization results data
        output_dir: Directory to save the report and plots
        template: Report template to use (currently supports 'standard' only)
    """
    # Ensure output directory exists
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"Created output directory: {output_dir}")
    
    # Check if data_path is a directory or file
    if os.path.isdir(data_path):
        # If directory, find all CSV files
        result_files = glob.glob(os.path.join(data_path, "*.csv"))
        if not result_files:
            print(f"Error: No CSV files found in directory {data_path}")
            return
    else:
        # Single file
        if not os.path.exists(data_path):
            print(f"Error: File {data_path} does not exist")
            return
        result_files = [data_path]
    
    # Load data
    combined_data = load_simulation_data(result_files)
    
    # Perform analysis
    summary = generate_summary_statistics(combined_data)
    
    # Generate plots
    metrics_to_plot = ['rtp', 'variance', 'hit_frequency', 'bonus_frequency']
    for metric in metrics_to_plot:
        plot_metric_distribution(combined_data, metric, output_dir)
    
    # Generate report based on template
    if template.lower() == "standard":
        generate_markdown_report(summary, output_dir, result_files)
    else:
        print(f"Warning: Template '{template}' not recognized. Using standard template.")
        generate_markdown_report(summary, output_dir, result_files)
    
    print(f"\nReport generation completed. See results in: {output_dir}")


# --- Command Line Interface ---

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate reports from simulation result files.")
    parser.add_argument("result_files", nargs='+', help="Path(s) to simulation result CSV file(s).")
    parser.add_argument("-o", "--output-dir", default="reports", help="Directory to save the report and plots.")
    # Add arguments for report format (e.g., --format markdown/pdf) if needed

    args = parser.parse_args()

    # Create output directory if it doesn't exist
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)
        print(f"Created output directory: {args.output_dir}")

    # Load data
    combined_data = load_simulation_data(args.result_files)

    # Perform analysis
    summary = generate_summary_statistics(combined_data)

    # Generate plots
    metrics_to_plot = ['rtp', 'variance', 'hit_frequency', 'bonus_frequency']
    for metric in metrics_to_plot:
        plot_metric_distribution(combined_data, metric, args.output_dir)

    # Generate report
    generate_markdown_report(summary, args.output_dir, args.result_files)

    print("\nScript finished.")

# Example Usage:
# python scripts/generate_report.py data/simulation_results/*.csv -o reports/my_game_analysis